In [1]:
import pandas as pd
import numpy as np

In [5]:
df2 = pd.DataFrame({
    'A': 1.,
    'B': pd.Timestamp('20200102'),
    'C': pd.Series(1, index=list(range(4)),dtype='float32'),
    'D': np.array([3] * 4, dtype="int32"),
    'E': pd.Categorical(['test', 'train', 'test', 'train']),
    'F': 'Python',
    'G': [2,2,4,4],
    'H': [np.nan,2,4,np.nan]
    })
df2

     A          B    C  D      E       F  G    H
0  1.0 2020-01-02  1.0  3   test  Python  2  NaN
1  1.0 2020-01-02  1.0  3  train  Python  2  2.0
2  1.0 2020-01-02  1.0  3   test  Python  4  4.0
3  1.0 2020-01-02  1.0  3  train  Python  4  NaN

In [11]:
df2.nunique(axis=1, dropna=False)
# axis=1 contabiliza por linha
# dropna=False contabiliza o NaN

0    7
1    6
2    6
3    7
dtype: int64

In [12]:
df2.drop_duplicates() # Remove linhas duplicadas

     A          B    C  D      E       F  G    H
0  1.0 2020-01-02  1.0  3   test  Python  2  NaN
1  1.0 2020-01-02  1.0  3  train  Python  2  2.0
2  1.0 2020-01-02  1.0  3   test  Python  4  4.0
3  1.0 2020-01-02  1.0  3  train  Python  4  NaN

In [16]:
# Verificar por coluna mantendo a primeira linha
df2.drop_duplicates(subset='G', keep='last', )
# keep mantem a última / keep=False remove as duplicadas

     A          B    C  D      E       F  G    H
1  1.0 2020-01-02  1.0  3  train  Python  2  2.0
3  1.0 2020-01-02  1.0  3  train  Python  4  NaN