In [1]:
import pandas as pd
import numpy as np

In [3]:
datas = pd.date_range('20200101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=datas, columns=['Var_A','Var_B','Var_C','Var_D'])

In [5]:
df2 = pd.DataFrame({
    'A': 1.,
    'B': pd.Timestamp(20200102),
    'C': pd.Series(1, index=list(range(4)),dtype='float32'),
    'D': np.array([3] * 4, dtype="int32"),
    'E': pd.Categorical(['test', 'train', 'test', 'train']),
    'F': 'Python'
    })
df

               Var_A     Var_B     Var_C     Var_D
2020-01-01 -0.416072 -0.038138  2.257242  2.197180
2020-01-02  0.761424  0.585744  0.782642  0.158560
2020-01-03  1.473000  2.207841  0.100903  0.090709
2020-01-04 -1.694402  0.094375 -0.203131 -1.713356
2020-01-05  0.910238  0.166684 -0.050415  2.315441
2020-01-06  1.453782  0.315329  0.780922  0.834023

In [6]:
df.shape

(6, 4)

In [7]:
df.dtypes

Var_A    float64
Var_B    float64
Var_C    float64
Var_D    float64
dtype: object

In [8]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [11]:
df2.describe() # Somente dados num√©ricos

         A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

In [15]:
# Pegando 4 linhas de df e colocando 1 coluna nova.
df1 = df.reindex(index=datas[0:4], columns=list(df.columns) + ["Var_F"])
# Atribuindo valor (77) as 2 primeiras linhas na coluna nova.
df1.loc[datas[0]:datas[1], 'Var_F'] = 77
df1

               Var_A     Var_B     Var_C     Var_D  Var_F
2020-01-01 -0.416072 -0.038138  2.257242  2.197180   77.0
2020-01-02  0.761424  0.585744  0.782642  0.158560   77.0
2020-01-03  1.473000  2.207841  0.100903  0.090709    NaN
2020-01-04 -1.694402  0.094375 -0.203131 -1.713356    NaN

In [16]:
df1.dtypes

Var_A    float64
Var_B    float64
Var_C    float64
Var_D    float64
Var_F    float64
dtype: object

In [17]:
df1.describe()

          Var_A     Var_B     Var_C     Var_D  Var_F
count  4.000000  4.000000  4.000000  4.000000    2.0
mean   0.030988  0.712456  0.734414  0.183273   77.0
std    1.389217  1.032416  1.095697  1.598145    0.0
min   -1.694402 -0.038138 -0.203131 -1.713356   77.0
25%   -0.735654  0.061247  0.024895 -0.360307   77.0
50%    0.172676  0.340060  0.441772  0.124634   77.0
75%    0.939318  0.991268  1.151292  0.668215   77.0
max    1.473000  2.207841  2.257242  2.197180   77.0